const $=id=>document.getElementById(id), canvas=$('map'), ctx=canvas.getContext('2d');
let state=null, stops=[], preview=null, centre=[0,0], scale=65, width=1,height=1,dpr=1, fitted=false,drag=null,busy=false;
const fmt=(v,n=1)=>Number.isFinite(v)?v.toFixed(n):'—';
const message=t=>$('message').textContent=t;
async function post(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v}
async function action(fn){if(busy)return;busy=true;try{await fn()}catch(e){message(e.message)}finally{busy=false}}
function xy(x,y){return [width/2+(x-centre[0])*scale,height/2-(y-centre[1])*scale]}
function fit(){const cells=state?.room?.cells;if(!cells?.length)return;let loX=Infinity,loY=Infinity,hiX=-Infinity,hiY=-Infinity;for(const [x,y]of cells){loX=Math.min(loX,x);loY=Math.min(loY,y);hiX=Math.max(hiX,x);hiY=Math.max(hiY,y)}const r=state.room.resolution;centre=[(loX+hiX+1)*r/2,(loY+hiY+1)*r/2];scale=Math.min((width-100)/Math.max(2,(hiX-loX+1)*r),(height-120)/Math.max(2,(hiY-loY+1)*r));fitted=true;draw()}
function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;dpr=devicePixelRatio||1;canvas.width=width*dpr;canvas.height=height*dpr;draw()}
function line(points,color,w=2){if(!points?.length)return;ctx.strokeStyle=color;ctx.lineWidth=w;ctx.beginPath();points.forEach((p,i)=>{const q=xy(p[0],p[1]);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke()}
function marker(p,label,color){const [x,y]=xy(...p);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#09212a';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(label,x,y+4);ctx.textAlign='start'}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#0d1d26';ctx.fillRect(0,0,width,height);ctx.strokeStyle='#1b303c';ctx.lineWidth=1;for(let i=-40;i<=40;i++){const a=xy(i,0),b=xy(0,i);ctx.beginPath();ctx.moveTo(a[0],0);ctx.lineTo(a[0],height);ctx.moveTo(0,b[1]);ctx.lineTo(width,b[1]);ctx.stroke()}const room=state?.room;if(!room)return;const r=room.resolution;for(const [x,y,v]of room.cells||[]){const p=xy(x*r,y*r);ctx.fillStyle=v>=5?'#a7bec9':v<=-4?'#203e4b':'#40535d';ctx.fillRect(p[0],p[1]-r*scale,Math.max(1,r*scale+.5),Math.max(1,r*scale+.5))}
const layer=$('layer').value;if(layer!=='room'){const index=layer==='temperature'?2:3,pts=(room.environment||[]).filter(p=>Number.isFinite(p[index]));const values=pts.map(p=>p[index]),lo=Math.min(...values),hi=Math.max(...values);for(const p of pts){const [x,y]=xy(p[0],p[1]);const t=hi===lo?.5:(p[index]-lo)/(hi-lo);ctx.fillStyle=`hsla(${210-200*t},90%,60%,.5)`;ctx.beginPath();ctx.arc(x,y,Math.max(6,.15*scale),0,Math.PI*2);ctx.fill()}$('legend').textContent=pts.length?`${fmt(lo)}–${fmt(hi)} ${layer==='temperature'?'°C':'% RH'} · measured at rover positions`:'No environmental samples yet'}else $('legend').textContent='Mint arrow: rover front · Yellow: planned route';
line(room.live_path||room.path,'#61cbb377',1.5);line(preview?.path,'#ffc778',3);if(state.mission?.state==='active')line(state.mission.path,'#9dffe4',3);
stops.forEach((p,i)=>marker(p,String(i+1),'#ffc778'));if(preview?.start)marker(preview.start,'A','#75dac6');
const p=room.pose;if(p?.length>=3&&p.every(Number.isFinite)){const [x,y]=xy(p[0],p[1]),live=room.tracking==='tracking';ctx.save();ctx.translate(x,y);ctx.rotate(-(p[2]+room.heading_offset));ctx.fillStyle=live?'#75ffe0':'#ffc778';ctx.strokeStyle='#071c26';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-10,-11);ctx.lineTo(-5,0);ctx.lineTo(-10,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle=live?'#75ffe0':'#ffc778';ctx.font='bold 12px system-ui';ctx.fillText(live?'ROVER LIVE':'LAST / ESTIMATED POSITION',x+22,y-14)}}
function render(){if(!state)return;const mode=state.session.mode,m=state.mission,active=['active','paused'].includes(m.state)||(typeof calibrationRunning!=='undefined'&&calibrationRunning),localized=mode==='localization'&&m.localization?.ready&&state.room?.tracking==='tracking';$('connection').textContent=state.network?.connected?'Rover connected':'Rover offline';$('temp').textContent=fmt(state.latest?.temperature_c);$('humidity').textContent=fmt(state.latest?.humidity_percent);$('sensorAge').textContent=state.network?.connected?`Reading age ${fmt((state.latest?.environment_age_ms||0)/1000)} s`:'Last recorded readings · offline';$('mission').textContent=mode==='mapping'?(state.room?.tracking==='tracking'?'SCANNING · live room map':'Waiting for map tracking'):m.state==='offline'?'Ready to scan':`${m.state.toUpperCase()} · ${m.reason}`;if(mode==='mapping'&&state.room?.tracking==='tracking'&&$('message').textContent==='ROS is starting. Drive slowly once the live map appears.')message('Scan running. Hold the arrows to explore; release to stop.');
['step1','step2','step3'].forEach((id,i)=>$(id).classList.toggle('active',i===(active?2:mode==='localization'?1:0)));$('scan').disabled=active||busy;$('finish').disabled=mode!=='mapping'||!state.room?.cells?.length||busy;$('plan').disabled=mode!=='localization'||!state.room?.pose||!stops.length||active||busy;$('go').disabled=!localized||!preview||active||busy;$('go').textContent=$('return').checked?'Go & return':'Visit stops';$('undo').disabled=$('clear').disabled=active;$('return').disabled=active;document.querySelectorAll('[data-dir]').forEach(b=>b.disabled=active||mode!=='mapping');$('stopCount').textContent=`${stops.length} / 6`;$('stops').replaceChildren(...stops.map(p=>{const li=document.createElement('li');li.textContent=`${fmt(p[0],2)}, ${fmt(p[1],2)} m`;return li}));$('routeInfo').textContent=preview?`${fmt(preview.distance_m)} m · visit ${preview.order.filter(i=>i!==0).join(' → ')}${preview.return_home?' → A':''}`:'Choose stops, then find the route.';$('notice').textContent=state.stack.error||state.room?.reason||(mode==='mapping'?'Starting LiDAR mapping…':'Start a room scan to begin.');const p=state.room?.pose;$('position').textContent=p?`x ${fmt(p[0],2)} m · y ${fmt(p[1],2)} m · heading ${fmt((p[2]+state.room.heading_offset)*180/Math.PI,0)}°`:'Waiting for live position';$('actionTitle').textContent=mode==='localization'?'2 · Mark your stops':'1 · Scan the room';$('instruction').textContent=mode==='localization'?'Click clear floor to select stops. The rover will choose their order and return to the trip start.':'Hold the arrows to drive slowly. Release to stop. Revisit the starting area before finishing.';if(!fitted&&state.room?.cells?.length)fit();draw()}
let connectionError=null;
async function poll(){try{const r=await fetch('/api/state');const v=await r.json();if(!r.ok)throw Error(v.error);state=v;if(connectionError&&$('message').textContent===connectionError)message('Connection restored.');connectionError=null;render()}catch(e){$('connection').textContent='Waiting for dashboard';connectionError=e.message;message(connectionError)}setTimeout(poll,400)}
$('scan').onclick=()=>action(async()=>{await stopDrive();await post('/api/scan');stops=[];preview=null;fitted=false;message('ROS is starting. Drive slowly once the live map appears.')});
$('finish').onclick=()=>action(async()=>{await stopDrive();await post('/api/finish');preview=null;fitted=false;message('Map saved. Finding the rover on this map…')});
$('plan').onclick=()=>action(async()=>{preview=await post('/api/plan',{targets:stops,return_home:$('return').checked});message('Route preview ready. Go becomes available with a fresh live position.');render()});
$('go').onclick=()=>action(async()=>{await post('/api/go');message('Mission requested. STOP is always available.')});
$('stop').onclick=async()=>{await stopDrive();try{await post('/api/stop');message('Stop sent.')}catch(e){message(e.message)}};
$('undo').onclick=()=>{stops.pop();preview=null;render()};$('clear').onclick=()=>{stops=[];preview=null;render()};$('return').onchange=()=>{preview=null;render()};$('fit').onclick=fit;$('find').onclick=()=>{if(state?.room?.pose){centre=state.room.pose.slice(0,2);draw()}};$('zoomIn').onclick=()=>{scale*=1.25;draw()};$('zoomOut').onclick=()=>{scale/=1.25;draw()};$('layer').onchange=draw;
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,...centre];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){centre=[drag[2]-(e.clientX-drag[0])/scale,drag[3]+(e.clientY-drag[1])/scale];draw()}};canvas.onpointerup=e=>{if(!drag)return;const moved=Math.hypot(e.clientX-drag[0],e.clientY-drag[1]);drag=null;if(moved>6||state?.session.mode!=='localization'||['active','paused'].includes(state.mission.state))return;if(stops.length>=6){message('Six stops maximum for this demo.');return}const rect=canvas.getBoundingClientRect(),p=[centre[0]+(e.clientX-rect.left-width/2)/scale,centre[1]-(e.clientY-rect.top-height/2)/scale];const room=state.room,r=room.resolution,c=room.cells.find(c=>c[0]===Math.floor(p[0]/r)&&c[1]===Math.floor(p[1]/r));if(!c||c[2]!==-8){message('Click scanned open floor, away from walls.');return}stops.push(p);preview=null;message('Stop added. Click more points or find the best route.');render()};canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();scale=Math.max(8,Math.min(400,scale*Math.exp(-e.deltaY*.001)));draw()};
let wanted=null,generation=0,driveBusy=false;
const directions={forward:'left',backward:'right',left:'backward',right:'forward'};
async function pulse(g){if(typeof calibrationRunning!=='undefined'&&calibrationRunning){wanted=null;return;}if(!wanted||g!==generation||driveBusy)return;driveBusy=true;const sentAt=performance.now();try{await post('/api/drive',{direction:directions[wanted],duty:(wanted==='left'||wanted==='right')?255:180})}catch(e){wanted=null;message(e.message)}finally{driveBusy=false;if(wanted)setTimeout(()=>pulse(generation),Math.max(0,100-(performance.now()-sentAt)));else post('/api/drive',{direction:'stop'}).catch(()=>{})}}
async function stopDrive(){wanted=null;generation++;try{await post('/api/drive',{direction:'stop'})}catch(e){message(e.message)}}
document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();wanted=b.dataset.dir;b.setPointerCapture(e.pointerId);pulse(++generation)};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{if(wanted)stopDrive()}});$('manualStop').onclick=stopDrive;window.onblur=()=>{if(wanted)stopDrive()};document.onvisibilitychange=()=>{if(document.hidden&&wanted)stopDrive()};new ResizeObserver(resize).observe(canvas);poll();resize();
