// web/index_html.h
// -----------------------------------------------------------------------------
// AUTO-GENERATED from web/index.html. Do not edit this file by hand.
// Regenerate after editing the UI with:
//   python3 tools/gen_index_html.py     (see this folder's README.md)
//
// The teleop UI is stored in PROGMEM so it can be streamed straight to the
// TCP socket with WebServer::send_P() without a heap copy.
// -----------------------------------------------------------------------------
#ifndef PITDIVERS_WEB_INDEX_HTML_H
#define PITDIVERS_WEB_INDEX_HTML_H

#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"PITHTML(
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>PitDivers Teleop</title>
<style>
  :root {
    --bg: #0e1116; --panel: #171c24; --edge: #262d38;
    --ink: #e6edf3; --muted: #8b98a8;
    --accent: #2f81f7; --accent-press: #1f6feb;
    --stop: #d64550; --stop-press: #b23540; --ok: #3fb950; --warn: #d29922;
  }
  * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }
  html, body { margin: 0; height: 100%; }
  body {
    background: var(--bg); color: var(--ink);
    font: 15px/1.4 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    display: flex; flex-direction: column; align-items: center;
    padding: 14px; gap: 14px; user-select: none; touch-action: manipulation;
  }
  header { width: 100%; max-width: 420px; display: flex; align-items: center; justify-content: space-between; }
  h1 { font-size: 17px; margin: 0; letter-spacing: .3px; }
  .status { display: flex; align-items: center; gap: 7px; font-size: 13px; color: var(--muted); }
  .dot { width: 10px; height: 10px; border-radius: 50%; background: var(--warn); box-shadow: 0 0 8px currentColor; }
  .dot.on { background: var(--ok); } .dot.off { background: var(--stop); }

  .pad {
    width: 100%; max-width: 420px;
    display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px;
  }
  .btn {
    appearance: none; border: 1px solid var(--edge); border-radius: 16px;
    background: var(--panel); color: var(--ink);
    font-size: 28px; font-weight: 600; padding: 26px 0;
    display: flex; align-items: center; justify-content: center;
    transition: background .05s, transform .05s;
  }
  .btn:active, .btn.held { background: var(--accent-press); border-color: var(--accent); transform: scale(.97); }
  .btn.wide { grid-column: 1 / -1; }
  .btn.stop { background: var(--stop); border-color: var(--stop); }
  .btn.stop:active { background: var(--stop-press); }
  .empty { visibility: hidden; }

  .speed { width: 100%; max-width: 420px; background: var(--panel); border: 1px solid var(--edge); border-radius: 16px; padding: 14px 16px; }
  .speed .row { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 8px; }
  .speed b { font-size: 20px; }
  input[type=range] { width: 100%; accent-color: var(--accent); height: 30px; }

  .log { width: 100%; max-width: 420px; font: 12px/1.5 ui-monospace, Menlo, Consolas, monospace;
    color: var(--muted); background: var(--panel); border: 1px solid var(--edge);
    border-radius: 12px; padding: 10px 12px; min-height: 42px; word-break: break-all; }
  .hint { color: var(--muted); font-size: 12px; max-width: 420px; text-align: center; }
</style>
</head>
<body>
  <header>
    <h1>PitDivers &mdash; Teleop</h1>
    <div class="status"><span id="dot" class="dot"></span><span id="stat">connecting&hellip;</span></div>
  </header>

  <div class="pad">
    <div class="empty"></div>
    <button class="btn" data-cmd="F">&#9650;</button>
    <div class="empty"></div>

    <button class="btn" data-cmd="L">&#9664;</button>
    <button class="btn stop" data-cmd="S" data-tap="1">STOP</button>
    <button class="btn" data-cmd="R">&#9654;</button>

    <div class="empty"></div>
    <button class="btn" data-cmd="B">&#9660;</button>
    <div class="empty"></div>
  </div>

  <div class="speed">
    <div class="row"><span>Speed</span><b id="spdLabel">70%</b></div>
    <input id="spd" type="range" min="0" max="9" step="1" value="7">
  </div>

  <div id="log" class="log">&hellip;</div>
  <div class="hint">Hold a direction to drive. Release (or STOP) to halt. Keyboard: W&nbsp;A&nbsp;S&nbsp;D / arrows.</div>

<script>
(function () {
  var WS_PORT = 84;
  var HEARTBEAT_MS = 250;           // must stay under the firmware watchdog (1500 ms)
  var ws = null, held = null, hbTimer = null, reconnectTimer = null;

  var dot = document.getElementById('dot');
  var stat = document.getElementById('stat');
  var logEl = document.getElementById('log');
  var spd = document.getElementById('spd');
  var spdLabel = document.getElementById('spdLabel');

  function log(msg) { logEl.textContent = msg; }
  function setStatus(cls, text) { dot.className = 'dot ' + cls; stat.textContent = text; }

  function send(c) { if (ws && ws.readyState === WebSocket.OPEN) ws.send(c); }

  // ---- WebSocket lifecycle ------------------------------------------------
  function connect() {
    clearTimeout(reconnectTimer);
    var url = 'ws://' + location.hostname + ':' + WS_PORT + '/';
    setStatus('', 'connecting…');
    try { ws = new WebSocket(url); } catch (e) { scheduleReconnect(); return; }

    ws.onopen = function () {
      setStatus('on', 'connected');
      send(String(spd.value));      // push current speed on connect
    };
    ws.onmessage = function (ev) {
      log(ev.data);
      if (ev.data === 'BUSY') setStatus('off', 'busy (another driver)');
    };
    ws.onclose = function () { setStatus('off', 'disconnected'); stopHeartbeat(); scheduleReconnect(); };
    ws.onerror = function () { try { ws.close(); } catch (e) {} };
  }
  function scheduleReconnect() { reconnectTimer = setTimeout(connect, 800); }

  // ---- Hold-to-drive ------------------------------------------------------
  function startHeartbeat(cmd) {
    stopHeartbeat();
    held = cmd;
    send(cmd);
    hbTimer = setInterval(function () { send(cmd); }, HEARTBEAT_MS);
  }
  function stopHeartbeat() {
    if (hbTimer) { clearInterval(hbTimer); hbTimer = null; }
    if (held) { held = null; send('S'); }
  }

  document.querySelectorAll('.btn').forEach(function (b) {
    var cmd = b.getAttribute('data-cmd');
    var tap = b.getAttribute('data-tap');   // STOP is a tap, not a hold

    if (tap) {
      b.addEventListener('pointerdown', function (e) { e.preventDefault(); stopHeartbeat(); send('S'); });
      return;
    }
    b.addEventListener('pointerdown', function (e) {
      e.preventDefault(); b.classList.add('held'); startHeartbeat(cmd);
    });
    var release = function () { b.classList.remove('held'); if (held === cmd) stopHeartbeat(); };
    b.addEventListener('pointerup', release);
    b.addEventListener('pointerleave', release);
    b.addEventListener('pointercancel', release);
  });

  // ---- Speed slider -------------------------------------------------------
  spd.addEventListener('input', function () {
    spdLabel.textContent = (spd.value * 10) + '%';
    send(String(spd.value));       // firmware applies it on the next F/B/L/R
  });

  // ---- Keyboard -----------------------------------------------------------
  var keyMap = { KeyW: 'F', ArrowUp: 'F', KeyS: 'B', ArrowDown: 'B',
                 KeyA: 'L', ArrowLeft: 'L', KeyD: 'R', ArrowRight: 'R' };
  window.addEventListener('keydown', function (e) {
    if (e.repeat) return;
    if (e.code === 'Space') { e.preventDefault(); stopHeartbeat(); send('S'); return; }
    var cmd = keyMap[e.code];
    if (cmd) { e.preventDefault(); startHeartbeat(cmd); }
  });
  window.addEventListener('keyup', function (e) {
    var cmd = keyMap[e.code];
    if (cmd && held === cmd) stopHeartbeat();
  });

  // Safety: stop if the tab is hidden or loses focus.
  document.addEventListener('visibilitychange', function () { if (document.hidden) stopHeartbeat(); });
  window.addEventListener('blur', stopHeartbeat);

  connect();
})();
</script>
</body>
</html>
)PITHTML";

static const size_t INDEX_HTML_LEN = sizeof(INDEX_HTML) - 1;

#endif // PITDIVERS_WEB_INDEX_HTML_H
