#!/usr/bin/env python3
"""Regenerate web/index_html.h from web/index.html.

The teleop UI is authored in web/index.html and compiled into the firmware as a
PROGMEM string (web/index_html.h). Run this after editing the HTML:

    cd firmware/controlWS
    python3 tools/gen_index_html.py

It is intentionally dependency-free (standard library only).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent          # firmware/controlWS/
SRC = HERE / "web" / "index.html"
DST = HERE / "web" / "index_html.h"
DELIM = "PITHTML"

HEADER = '''// web/index_html.h
// -----------------------------------------------------------------------------
// AUTO-GENERATED from web/index.html. Do not edit this file by hand.
// Regenerate after editing the UI with:
//   python3 tools/gen_index_html.py     (see this folder's README.md)
//
// The teleop UI is stored in PROGMEM so it can be streamed straight to the
// TCP socket with WebServer::send_P() without a heap copy.
// -----------------------------------------------------------------------------
#ifndef PITDIVERS_WEB_INDEX_HTML_H
#define PITDIVERS_WEB_INDEX_HTML_H

#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"{delim}(
{src}){delim}";

static const size_t INDEX_HTML_LEN = sizeof(INDEX_HTML) - 1;

#endif // PITDIVERS_WEB_INDEX_HTML_H
'''


def main() -> None:
    html = SRC.read_text(encoding="utf-8")
    if f'){DELIM}"' in html:
        raise SystemExit(f"index.html contains the raw-string delimiter '){DELIM}\"'; "
                         "choose a different DELIM in this script.")
    DST.write_text(HEADER.format(delim=DELIM, src=html), encoding="utf-8")
    print(f"wrote {DST.relative_to(HERE)} ({len(html)} bytes of HTML)")


if __name__ == "__main__":
    main()
